<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name') }}</title>
 
  <!-- Scripts -->
  <script src="{{ asset('js/app.js') }}"></script>
  <link rel="icon" type="image/png"  href="{{url('/img/web_logo.png')}}">
  <!-- Fonts -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <style>
    
    /* Create three equal columns that floats next to each other */
    .column {
        float: left;
        width: 20%;
        height: auto;
    }
    .clearance_row{
        float:right;
        margin-right: 1px;
        border: 2px solid;
        height: auto;
        margin-bottom: 20px;
        width: 100% !important;
    }
    p{
        white-space: nowrap; 
        width: auto;
        height: auto; 
        overflow: hidden;
        text-overflow: clip;
        text-align: center;
        background-color: #e9ecef;
    }
    .clearance_body{
        width:100%;
    padding-top: 50px;
    }
    table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: center;
  padding: 8px;
  font-size: 12px;
}
th{
    background-color: rgb(198, 198, 198);
}

tr:nth-child(even) {
  background-color: #D6EEEE;
}
.page-break {
    page-break-after: always;
}
.card{
padding-left: 96px;
width: 76%;
float: left;
}
</style>
 </head>
<body>
    <div class="clearance_body">
        <h4 style="text-align:center"><b>Our Lady of Lourdes College Foundation<br>
            E-Clearance</b><br>
            <span style="text-align:center; font-size:15px; ">Daet Camarines Norte</span>
        </h4>
        <hr style="background-color: black; height: 1px">
        <p style="text-align: right; font-size: 10px;  background-color: white; padding-bottom: 10px;padding-right: 96px; padding-top: 10px">Date Generated: {{date('M,d,D,Y,g:i A')}}<br>
            Generated By: {{Auth::user()->name}} 
        </p>
        <div  class="card">
            <div class="card-header">
                <h5 style="text-align:center;font-weight: bold; padding-bottom: 12px">Completed Clearance List</h5> 
            </div>
            <div  class="card-body">
                <table class="table table-bordered">
                    <thead> 
                        <tr>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Course</th>
                            <th>Year Level</th>
                            <th>Semester</th>
                            <th>School ID</th>
                            <th>Clearance</th>
                        </tr>
                    </thead> 
                    <tbody>
                        @php
                            $index_count = 1;
                        @endphp 
                        @foreach($complete_request as $user)
                            <?php
                                $approve_count = 0;
                                $status_total = 0;
                            ?> 
                            @foreach($user->status as $instructor_status_count)
                                @if($instructor_status_count == "APPROVED")
                                    <?php
                                        $approve_count++;
                                    ?>
                                @endif
                                @if($instructor_status_count !== "APPROVED" || $instructor_status_count == "APPROVED")
                                    <?php
                                        $status_total++;
                                    ?>
                                @endif
                            @endforeach
                            <?php
                            if($user->guidance_councilor == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->student_org_treasurer == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->librarian == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->dean_of_student_affair == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->dean_principal == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->registrar == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->accounting_assessment == "APPROVED"){
                                $approve_count++;
                            }
                            //
                            if($user->guidance_councilor == "APPROVED" || $user->guidance_councilor !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->student_org_treasurer == "APPROVED" || $user->student_org_treasurer !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->librarian == "APPROVED" || $user->librarian !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->dean_of_student_affair == "APPROVED" || $user->dean_of_student_affair !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->dean_principal == "APPROVED" || $user->dean_principal !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->registrar == "APPROVED" || $user->registrar !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->accounting_assessment == "APPROVED" || $user->accounting_assessment !== "APPROVED"){
                                $status_total++;
                            }
                                $pass_approved_total_value =  $approve_count;
                                $pass_status__total_value = $status_total;
                            ?>
                            @if($pass_approved_total_value == $pass_status__total_value)
                                <tr>
                                    <td>{{$index_count++}} </td> 
                                    <td>{{$user->name}}</td>
                                        @foreach($course as $course_id)
                                            @if($course_id->id == $user->course)
                                                <td>{{$course_id->course_acronym}}</td>
                                            @endif
                                        @endforeach
                                    <td>{{$user->year_lvl}}</td>
                                    <td>{{$user->semester}}</td>
                                    <td>{{$user->school_id}}</td>
                                    <td style="color: green"><b>Completed</b></td>             
                                </tr>
                            @endif
                        @endforeach 
                    </tbody>
                </table>
            </div>  
        </div>
    </div> 
    <div class="page-break"></div>
    <div class="clearance_body">

        <h4 style="text-align:center"><b><br>Our Lady of Lourdes College Foundation<br>E-Clearance</b><br>
            <span style="text-align:center; font-size:15px; ">Daet Camarines Norte</span>
        </h4>
        <hr style="background-color: black; height: 1px">
        <p style="text-align: right; font-size: 10px;  background-color: white; padding-bottom: 10px;padding-right: 96px; padding-top: 10px">Date Generated: {{date('M,d,D,Y,g:i A')}}<br>
            Generated By: {{Auth::user()->name}} 
        </p>
        <div  class="card">
            <div class="card-header">
                <h5 style="text-align:center;font-weight: bold; padding-bottom: 12px">Incomplete Clearance List</h5> 
            </div>
            <div  class="card-body">
                <table class="table table-bordered">
                    <thead> 
                        <tr>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Course</th>
                            <th>Year Level</th>
                            <th>Semester</th>
                            <th>School ID</th>
                            <th>Clearance</th>
                        </tr>
                    </thead> 
                    <tbody>
                        @php
                            $index_count = 1;
                        @endphp 
                        @foreach($complete_request as $user)
                            <?php
                                $approve_count = 0;
                                $status_total = 0;
                            ?> 
                            @foreach($user->status as $instructor_status_count)
                                @if($instructor_status_count == "APPROVED")
                                    <?php
                                        $approve_count++;
                                    ?>
                                @endif
                                @if($instructor_status_count !== "APPROVED" || $instructor_status_count == "APPROVED")
                                    <?php
                                        $status_total++;
                                    ?>
                                @endif
                            @endforeach
                            <?php
                            if($user->guidance_councilor == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->student_org_treasurer == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->librarian == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->dean_of_student_affair == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->dean_principal == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->registrar == "APPROVED"){
                                $approve_count++;
                            }
                            if($user->accounting_assessment == "APPROVED"){
                                $approve_count++;
                            }
                            //
                            if($user->guidance_councilor == "APPROVED" || $user->guidance_councilor !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->student_org_treasurer == "APPROVED" || $user->student_org_treasurer !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->librarian == "APPROVED" || $user->librarian !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->dean_of_student_affair == "APPROVED" || $user->dean_of_student_affair !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->dean_principal == "APPROVED" || $user->dean_principal !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->registrar == "APPROVED" || $user->registrar !== "APPROVED"){
                                $status_total++;
                            }
                            if($user->accounting_assessment == "APPROVED" || $user->accounting_assessment !== "APPROVED"){
                                $status_total++;
                            }
                                $pass_approved_total_value =  $approve_count;
                                $pass_status__total_value = $status_total;
                            ?>
                            @if($pass_approved_total_value !== $pass_status__total_value)
                                <tr>
                                    <td>{{$index_count++}} </td> 
                                    <td>{{$user->name}}</td>
                                        @foreach($course as $course_id)
                                            @if($course_id->id == $user->course)
                                                <td>{{$course_id->course_acronym}}</td>
                                            @endif
                                        @endforeach
                                    <td>{{$user->year_lvl}}</td>
                                    <td>{{$user->semester}}</td>
                                    <td>{{$user->school_id}}</td>
                                    <td style="color: red"><b>Incomplete</b></td>             
                                </tr>
                            @endif
                        @endforeach 
                    </tbody>
                </table>
            </div>  
        </div>
    </div>
</body>
</html>

